from Autodesk.Revit.DB import BuiltInCategory

category_mapping = {
    "Casework": BuiltInCategory.OST_Casework,
    "Ceilings": BuiltInCategory.OST_Ceilings,
    "Columns": BuiltInCategory.OST_Columns,
    "Curtain Panels": BuiltInCategory.OST_CurtainWallPanels,
    "Curtain Wall Mullions": BuiltInCategory.OST_CurtainWallMullions,
    "Detail Items": BuiltInCategory.OST_DetailComponents,
    "Doors": BuiltInCategory.OST_Doors,
    "Ducts": BuiltInCategory.OST_DuctSystem,
    "Electrical Equipment": BuiltInCategory.OST_ElectricalEquipment,
    "Electrical Fixtures": BuiltInCategory.OST_ElectricalFixtures,
    "Floors": BuiltInCategory.OST_Floors,
    "Furniture": BuiltInCategory.OST_Furniture,
    "Furniture Systems": BuiltInCategory.OST_FurnitureSystems,
    "Generic Models": BuiltInCategory.OST_GenericModel,
    "Grids": BuiltInCategory.OST_Grids,
    "Gutters": BuiltInCategory.OST_Gutter,
    "Lighting Fixtures": BuiltInCategory.OST_LightingFixtures,
    "Levels": BuiltInCategory.OST_Levels,
    "Materials": BuiltInCategory.OST_Materials,
    "Mass": BuiltInCategory.OST_Mass,
    "Mechanical Equipment": BuiltInCategory.OST_MechanicalEquipment,
    "Parking": BuiltInCategory.OST_Parking,
    "Pipes": BuiltInCategory.OST_PipingSystem,
    "Plumbing Fixtures": BuiltInCategory.OST_PlumbingFixtures,
    "Railings": BuiltInCategory.OST_StairsRailing,
    "Roofs": BuiltInCategory.OST_Roofs,
    "Rooms": BuiltInCategory.OST_Rooms,
    "Site": BuiltInCategory.OST_Site,
    "Specialty Equipment": BuiltInCategory.OST_SpecialityEquipment,
    "Sprinklers": BuiltInCategory.OST_FireProtection,
    "Stairs": BuiltInCategory.OST_Stairs,
    "Structural Columns": BuiltInCategory.OST_StructuralColumns,
    "Structural Foundations": BuiltInCategory.OST_StructuralFoundation,
    "Structural Framing": BuiltInCategory.OST_StructuralFraming,
    "Topography": BuiltInCategory.OST_Topography,
    "Toposolids": BuiltInCategory.OST_Toposolid,
    "Walls": BuiltInCategory.OST_Walls,
    "Windows": BuiltInCategory.OST_Windows,
}
